# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subgraph_isomorphism_interface <- function(pattern, match, algorithm, direction, vertex_atributes_g1, vertex_atributes_g2, type_graph, constraint, pattern_vertex, match_vertex, degreesorted) {
    .Call(`_Sics_subgraph_isomorphism_interface`, pattern, match, algorithm, direction, vertex_atributes_g1, vertex_atributes_g2, type_graph, constraint, pattern_vertex, match_vertex, degreesorted)
}

