# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' does something
#' @param pattern does something
#' @param match does something
#' @param algorithm does something
#' @param direction does something
#' @param vertex_atributes_g1 does something
#' @param vertex_atributes_g2 does something
#' @param type_graph does something
#' @param constraint does something
#' @param pattern_vertex does something
#' @param match_vertex does something
#' @param degreesorted does something
subgraph_isomorphism_interface <- function(pattern, match, algorithm, direction, vertex_atributes_g1, vertex_atributes_g2, type_graph, constraint, pattern_vertex, match_vertex, degreesorted) {
    .Call(`_Sics_subgraph_isomorphism_interface`, pattern, match, algorithm, direction, vertex_atributes_g1, vertex_atributes_g2, type_graph, constraint, pattern_vertex, match_vertex, degreesorted)
}

